### ISSUE TITLE
Initial workflow happens after "offset" interval which means a long wait time for larger offsets

### ISSUE THREAD

**Issue by anish749** [spotify/styx#545] opened 2018-08-13 15:19 UTC
During workflow initialisation, the next trigger instant is `offset` duration _after_ the current time. This means that for larger values of offset (like 30 days, 90 days) the natural trigger would be after 30 days with the partition instant being the current time. While for smaller values (a few hours or 1 day offsets) this works well, but makes it harder to test and iterate fast for larger offsets. Larger offset values are typically used for tracking lagging metrics.

Changing the [initial trigger](https://github.com/spotify/styx/blob/master/styx-api-service/src/main/java/com/spotify/styx/api/workflow/WorkflowInitializer.java#L96) to subtract the offset would solve the issue and would allow for a trigger to happen at the next schedule interval but with partition value which is offset by the given interval behind time. However, this would break the API as documented, since the workflow should trigger after the offset duration, according to the doc.

Proposal:
Add a separate flag in workflow which would allow only the initial trigger to happen at the next schedule interval. (At the next hour if hourly, at midnight, if daily, etc) with a partition value at 'offset' duration back. The following natural triggers can however happen every 'schedule'.

**Comment by honnix** [comment] 2018-08-14 06:31
Thanks for reporting. Having a flag indicating whether to subtract or add offset sounds good to me.

**Comment by ulzha** [comment] 2018-08-14 12:01
Unclear at "subtract or add", that's what the offset's sign is for.

I think the issue is just about starting to trigger the workflow ASAP after creation, instead of waiting for offset duration.

I think in the documentation we aren't really stating that the first trigger for a newly created offset workflow will occur only after offset duration. Maybe let's b̶r̶e̶a̶k̶fix it? I haven't heard arguments in favor of the current behavior, only complaints.

**Comment by honnix** [comment] 2018-08-14 12:03
That was my initial reaction as well. We could just alway subtract offset to get the first `next natural trigger`, and that means an immediate triggering of a partition.

**Comment by danielnorberg** [comment] 2019-02-07 05:27
This should be fixed now.

**Closed by danielnorberg** 2019-02-07 05:27 UTC
Labels: enhancement

**Comment by anish749** [comment] 2019-02-08 09:22
thanks @danielnorberg
